service: serverless-layer
frameworkVersion: '3'

package:
  individually: true
  excludeDevDependencies: true
  
provider:
  name: aws
  runtime: nodejs18.x
 
layers:
  NodeModules:
    path: modules
    name: ${sls:stage}-modules
    description: NodeJS Modules