name: Deploy

on:
  push:
    branches: [ "develop" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies for AWS
        run: |
          cd aws/
          npm install

      - name: Install dependencies for COMMON
        run: |
          cd common/
          npm install
          
      - name: Install dependencies for DATABASE
        run: |
          cd database/
          npm install
