name: Build Lambda Layer

on:
  push:
    branches: [ "develop" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies for Node Modules
        run: |
          cd modules/
          npm install
          
      - name: Deploy using sls
        run: |
          npm install -D
          npx sls deploy
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
